ResNet:
  dcn_v2_stages:
  - '1'
  - '2'
  - '3'
  depth: '50'
  freeze_at: '0'
  norm_type: bn
  num_stages: '4'
  return_idx:
  - '0'
  - '1'
  - '2'
  - '3'
_BASE_:
- ../datasets/vtx_coco_detection.yml
- ../runtime.yml
- ../cascade_rcnn/_base_/optimizer_1x.yml
- ../cascade_rcnn/_base_/cascade_rcnn_r50_fpn.yml
- ../cascade_rcnn/_base_/cascade_fpn_reader.yml
weights: output/cascade_rcnn_dcn_r50_fpn_1x_coco/model_final
