EvalReader:
  collate_batch: false
_BASE_:
- ../datasets/vtx_coco_detection.yml
- ../runtime.yml
- _base_/optimizer_270e.yml
- _base_/yolov3_darknet53.yml
- _base_/yolov3_reader.yml
snapshot_epoch: 5
weights: output/yolov3_darknet53_270e_voc/model_final
